#!/usr/bin/env php
<?php

if (php_sapi_name() !== 'cli') {
    echo "This script must be called from the command line".PHP_EOL;
    exit(1);
}

require __DIR__ . '/vendor/autoload.php';

$commandName = isset($argv[1]) ? $argv[1] : 'help';
$commandClass = '\\Tabulate\\Commands\\'.ucfirst($commandName).'Command';
if (!class_exists($commandClass)) {
    echo "ERROR: Command '$commandName' not valid.".PHP_EOL;
    $commandClass = '\\Tabulate\\Commands\\HelpCommand';
}

array_shift($argv);
$command = new $commandClass($argv);
$command->run();
